name: Update EPG

on:
  workflow_dispatch:

  schedule:
    - cron: '30 3 * * *'

permissions:
  contents: write

jobs:
  update-epg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Clone iptv-org/epg
        run: |
          git clone --depth 1 https://github.com/iptv-org/epg.git epg

      - name: Install dependencies
        working-directory: epg
        run: npm install

      - name: Generate EPG
        working-directory: epg
        run: |
          npm run grab --- \
            --sites=epg.telemach.ba,maxtv.hrvatskitelekom.hr,mtel.ba,mts.rs,tvarenasport.com,tvarenasport.hr \
            --output=../guide.xml

      - name: Remap EPG IDs
        run: |
          python3 scripts/remap_epg.py guide.xml mappings.json

      - name: Commit guide.xml
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add guide.xml
          git commit -m "Update EPG" || echo "No changes"
          git push
